### PR TITLE
Update Repo with Betaflight (01/05/2017)

### PR DESCRIPTION
**Pull request by HaseebNain**
This pull will bring the ThrustUAV betaflight repo up to date with the Betaflight/betaflight repo as of (01/05/2017)

### CODE REVIEW

**Comment by HaseebNain** [comment]
Need to update RIOTFC and PODIUM as well as reinstate defaults.

**Comment by HaseebNain** [comment]
All previous features working, will need to flight test.

**Comment by HaseebNain** [comment]
Stop reading these, Chris.

**Comment by Hazakins** [comment]
but why?

**Pull request merged**
